### ISSUE TITLE
74HC595BQ 16-DHVQFN (2.5x3.5)

### ISSUE THREAD

**Issue by dunk8888** [zakqwy/RRRYYYYYgYgGGBgB#1]
Hi,Great project! Ime in the process of making this project. Just a question regards to the 74hC595BQ. 
I can only find the package for this in this size 2.6x3.6. 
Will this be much of a problem,will this fit with a squeeze do you think?
Thanks

**Comment by zakqwy** [comment]
Glad you're building one! 2.6x3.6 shouldn't be a problem; I stretched the pads a bit for ease of hand soldering so that will fit. I'm guessing it's actually the same part, if I recall the 2.5x3.5 was a nominal dimension. Good luck, let me know if you have any issues with the build.

**Comment by dunk8888** [comment]
Oh right ok,i did see the pads where quite long,i`me very good at soldering and i enjoy it. I find it kind of therapeutic so that side of things should be ok.
Sourcing the leds will be a pain for me i think,although i could use alternatives as it doesnt have to be spot on for me.I just enjoy the build.
Thanks for getting back to me so quickly i can get on now with ordering the parts.
Duncan

**Comment by dunk8888** [comment]
This will be ok will it?

http://www.ebay.co.uk/itm/5PCS-74HC595BQ-115-IC-8BIT-SHIFT-REGISTER-16-DHVQFN-74HC595BQ-HC595-74HC595-/192143311090?hash=item2cbca240f2:g:E9UAAOSwcBhWYAva

**Comment by zakqwy** [comment]
yup, those shift registers look good. and any 0402 LEDs should fit; the PicoLEDs just have enough different colors to provide a neat effect.

**Comment by dunk8888** [comment]
In fact this is the one ile get its quicker postage.
http://uk.rs-online.com/web/p/counters-shift-registers/7918753/?searchTerm=74HC595BQ&relevancy-data=636F3D3126696E3D4931384E53656172636847656E65726963266C753D656E266D6D3D6D61746368616C6C7061727469616C26706D3D5E2E2A2426706F3D31333326736E3D592673743D43415443485F414C4C5F44454641554C542673633D592677633D4E4F4E45267573743D373448433539354251267374613D37344843353935425126

**Comment by dunk8888** [comment]
I will try get the picoLEDs if i can source them around my end,digikey could be quite costly,with £10 postage to start with ive not looked properly yet,ile let you know how i get on. thanks
