### ISSUE TITLE
Leds?

### ISSUE THREAD

**Issue by dunk8888** [zakqwy/RRRYYYYYgYgGGBgB#2]
Hi,do all the led gnd go through a resistor to gnd? ime trying a breadboard version now?
Also do you have a schematic with the resistor part showing? Thanks

**Comment by zakqwy** [comment]
yup, each LED has its own resistor. value depends on the LED (vdrop and current draw).

**Comment by zakqwy** [comment]
to clarify, the LEDs go through resistor networks to save space, then a few of em go through another resistor to further limit current.

**Comment by dunk8888** [comment]
Yes ive got it running now,its great,ive even just finished my own pcb
version,its a bit bigger than yours and uses bigger shift registers,i have
loads from a few years ago and ive been wanting to use them so ime using
them with this project,i knew they would come in handy.

The pcb ive designed is just rough at minute ive not decided yet on the
final design.Ime going to make one for standard through hole leds too.

**Comment by zakqwy** [comment]
awesome!! Thanks for posting this -- if you snap any photos, link to em here so I can take a look. would be neat to see another blinktronicator in the wild.
